### PR TITLE
#161042851 Create a view all products page for shop attendant

### PR DESCRIPTION
**Pull request by codeMarble254**
#### What does this PR do?
This PR creates a view all products page for a shop attendant
#### Description of Task to be completed?
The main tasks to be completed are:\
Creation of a main categories panel\
Creation of a a shopping cart modal\
Creation of product details modals\
Creation of a navigation bar
#### How should this be manually tested?
To test this page, clone my repository using the link ```https://github.com/codeMarble254/Store-Manager.git```
Then open the terminal and change the current directory to Store-Manager\
Switch to the ft-view-products-UI-161042851 branch using ```git checkout ft-view-products-UI-161042851```
Finally, launch home.html
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
#161042851
#### Screenshots (if appropriate)
screenshot from 2018-10-09 17-03-06

screenshot from 2018-10-09 17-03-08

screenshot from 2018-10-09 17-03-14

#### Questions:
How does the UI look? Any improvements i can make?

### CODE REVIEW

**Comment by Mukuria-Samuel** [comment]
Good job, colors are subtle and not distracting.

**Comment by kelvinwm** [comment]
Good work

**Comment by Arusey** [comment]
Looks good

**Comment by sharkdevs** [comment]
looking good bro

**Comment by SelaDanti** [comment]
Awesome work

**Comment by vmuthabuku** [comment]
Nice one

**Pull request merged**
